### PR TITLE
introduce hasKnownResult to optimize several parsers.

### PR DESCRIPTION
**Pull request by johnynek**
Often, we can statically see what the result value will be if a parser succeeds.

If we know this, can optimize map, select and flatMap.

In particular, we can avoid reallocating a parser inside each flatMap.

Most users should avoid using flatMap anyway, but in a library function, you might need flatMap but want to get the optimization when the user passes you a constant parser.

### CODE REVIEW

**Review by regadas — APPROVED** [review]
It will be interesting to see new benchmark numbers.

**Comment by regadas** [comment]
@johnynek could you rebase this?

**Comment by johnynek** [comment]
Yes! I will do. Thanks for the review.

Note, this optimization will mostly apply to flatMap, and most parser don't need flatMap (e.g. our json benchmarks don't use flatMap). But still, I thought it was worth trying to limit the worst case.

**Comment by johnynek** [comment]
@regadas let me know if this looks good.

**Review by regadas — APPROVED** [review]
Looks great!

**Pull request merged**
