### PR TITLE
Out with 3.0.0-M3, in with Scala 3.0.0-RC2

### PR DESCRIPTION
**Pull request by VlachJosef**
Helping with https://github.com/http4s/http4s/pull/4681

### CODE REVIEW

**Review by johnynek — APPROVED** [review]
Thank you!

**Comment by kubukoz** [comment]
Hello friends, can we get this released? Can I help?

**Comment by johnynek** [comment]
@kubukoz I'll publish after #193 is merged.

**Comment by johnynek** [comment]
@kubukoz https://github.com/typelevel/cats-parse/releases/tag/v0.3.2 should be on its way out now.

**Pull request merged**
