### PR TITLE
Add the ?: operator from #382

### PR DESCRIPTION
**Pull request by johnynek**
adds the operator conceived by @carueda in #382 and some associated laws.

### CODE REVIEW

**Comment by carueda** [comment]
Wonderful, thanks!!

**Review by carueda — APPROVED** [review]
Only comment is that there are no tests verifying expected errors, but I understand that's the general state of affairs, so no show-stopper at all.  Many thanks again for incorporating `?:` in this amazing library!

**Comment by johnynek** [comment]
The more I think about this one the more I am not sure...

pros:
  1. useful for clearer error messages
  2. allows avoiding introducing Parser0 to get left optionality.

cons:
  1. possibly cryptic syntax for users `?:` which part is optional left or right (left, same side as ?).
  2. methods ending in `:` can be confusing for new scala users (they are right associative).
  3. possibly we could solve this so that `foo.? ~ bar` does the right thing. We could potentially rewrite that so that. The questions, would it be safe to rewrite a `OneOf0(ls) ~ r` into `OneOf(ls.map(_.with1 ~ r))`? I thought maybe it wouldn't before since I had a similar law that failed. Even failing that, it could be that we can rewrite a `OneOf0(...)` ending in `Pure` to a `(oneOf(ls.init) ~ r) | (ls.last ~ r)`... If that rewrite is lawful, then this method isn't needed and we could just fix underlying syntax.

I'll experiment with the weaker rewrite in 3 in some laws. I am pretty sure the strong rewrite fails due to lack of backtracking, but maybe the weak one passes since `Pure` always backtracks and it is the last item in the oneOf.

**Comment by carueda** [comment]
I agree that `?:` could create unnecessary confusion for some users, especially given the other regular operators in it (in particular, the left-associativity of the common `~`). No need to incorporate the new operator.  I think users with that kind of need can just add an extension or something (as I'm doing already with just a couple of lines).

But I vote for somehow supporting enriched error reporting for `p1.? ~ p2.? ~ p3.? ~ p4.? ~ p5.? ~ pz`.

**Pull request closed without merging**
