### PR TITLE
Add initial mdoc support

### PR DESCRIPTION
**Pull request by regadas**
* `mdoc` compile is tied to `Compile / paradox`.
* `README.md` is now a symlink to `index.md`

### CODE REVIEW

**Comment by johnynek** [comment]
Thanks! We would need to also run mdoc in the CI no? or is it automatically done by doc? Did you very the CI fails if you break some code?

**Comment by regadas** [comment]
@johnynek I was trying to tie it to the compile task but it seems to be a little bit tricky... the easy way was to add `docs/mdoc` as one of the steps. CI should fail if code breaks.

We will need to limit the docs build to 2.12/2.13 though ... I'm seeing some issues with dotty.

**Comment by regadas** [comment]
@johnynek added a separate step for docs

**Comment by johnynek** [comment]
thanks @regadas ! I don't really know much about the sbt plugin we are using to generate the yml, but it seems like it is doing the right thing.

Thanks.

**Comment by johnynek** [comment]
Related to #7

**Pull request merged**
