### PR TITLE
Update version strings in index.md

### PR DESCRIPTION
**Pull request by johnynek**
Thank you for contributing to `cats-parse`!

This is a kind reminder to run `sbt prePR` and commit the changed files, if any, before submitting.

### CODE REVIEW

**Comment by johnynek** [comment]
let's wait to merge until the release has propagated and we can click on the documentation links.

**Comment by regadas** [comment]
It seems that javadoc jar's might not have been published 🤔

**Comment by regadas** [comment]
@johnynek smth is fishy here 🤔 I was looking at oss.sonatype.org and I can't see the latest `0.3.7` release there that's why we can resolve the javadoc URL. However, it is in fact available in https://repo1.maven.org/maven2/org/typelevel/cats-parse_2.13/0.3.7/

**Comment by armanbilge** [comment]
> smth is fishy here 🤔 I was looking at oss.sonatype.org

Everything is published via s01 as of a few months ago :)

https://s01.oss.sonatype.org/service/local/repositories/releases/archive/org/typelevel/cats-parse_2.13/0.3.7/cats-parse_2.13-0.3.7-javadoc.jar/!/cats/parse/index.html

Note there is also javadoc.io which syncs directly with Maven central.
https://javadoc.io/doc/org.typelevel/cats-parse_2.13/0.3.7/index.html

**Comment by regadas** [comment]
>Everything is published via s01 as of a few months ago

Missed this somehow, Thx!

**Comment by regadas** [comment]
@johnynek rebase this; I hope you don't mind me breaking in 🙏

**Pull request merged**
