### PR TITLE
Avoid oneOf reverse on List

### PR DESCRIPTION
**Pull request by regadas**
Just noticed this.

### CODE REVIEW

**Comment by johnynek** [comment]
I don't love passing mutable variables through a recursive loop. I'd rather either go all in and make a while loop to signal to the reader that we are in an imperative mode here, or just capture the buffer to make it clear there is only ever one mutable ListBuffer.

I'll merge this since you took the time, but I think it is worth thinking of three tiers of performance concerns:

1. cost to build parsers.
2. cost to run parsers.
3. cost to handle errors.

My belief is that it is 2 that by far dominates and that we shouldn't sacrifice much clarity and immutability in 1 or 3. On point 2 we should save our full budget for crazy tricks to maximize the performance of running (typically correct) parsers. On 3, note, when a parser fails, generally something will be reported to a user, and that will be very slow. So, a bit of slowness there if it results in clearer code, is probably fine.

**Review by johnynek — APPROVED** [review]
Added some comments, but I will merge this.

**Comment by regadas** [comment]
You convinced me with:
> I don't love passing mutable variables through a recursive loop. I'd rather either go all in and make a while loop to signal to the reader that we are in an imperative mode here, or just capture the buffer to make it clear there is only ever one mutable ListBuffer.

It's a very good argument and I totally agree with you here.

> I'll merge this since you took the time

I would be totally fine in closing this 😄  I value more reaching a good consensus and understanding on how do we want things to be.

Thank you!

**Comment by johnynek** [comment]
It's fine. I appreciate your PRs and all the help you've given.

**Pull request merged**
