### PR TITLE
Fix unclear SBT example in documentation

### PR DESCRIPTION
**Pull request by stephenjudkins**

### CODE REVIEW

**Review by regadas — COMMENTED** [review]
@stephenjudkins Thanks for this!

Technically this is not a typo, this how one would add it as a scala.js dep. Maybe we could reword this a bit so we could fit both?

**Comment by regadas** [comment]
```scala
// use this snippet for the JVM
libraryDependencies += "org.typelevel" %% "cats-parse" % "0.0.1"

// use this snippet for JS, or cross-building
libraryDependencies += "org.typelevel" %%% "cats-parse" % "0.0.1"
```

**Comment by stephenjudkins** [comment]
Yeah, I'm not certain what the right way would be here, but I would personally err on just using `%%` since that's what most Scala users (who aren't using scala.js) will default to. Your call!

**Comment by johnynek** [comment]
@stephenjudkins do you want to update the PR with @regadas suggestion? I agree it would be helpful for people less familar with these sbt esoterica.

**Pull request merged**
